# Generated by Django 5.2.2 on 2025-06-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumechecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
